site_name: Smart Pixels ML Docs
site_url: https://smart-pix.github.io
repo_url: https://github.com/smart-pix/smart-pix.github.io
use_directory_urls: false
nav:
  - Home: README.md
  - Usage: usage.md
  - API Reference:
      - Utils: api/utils.md
      - Models: api/models.md
      - Loss: api/loss.md
      - Data Generator: api/data_generator.md
      - Evaluate: api/evaluate.md
      - Plotting: api/plotting.md
  - Testing: testing.md
  - Visualization: plot.md
theme:
  name: material
  logo: Images/SmartPix.jpeg
  favicon: Images/SmartPix.jpeg
  features:
    - navigation.expand
    - navigation.top
    - content.code.copy
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - mdx_math
docs_dir: src
site_dir: docs
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
